BOOK_ORDER = [
    ("Rdz", "Księga Rodzaju"),
    ("Wj", "Księga Wyjścia"),
    ("Kpl", "Księga Kapłańska"),
    ("Lb", "Księga Liczb"),
    ("Pwt", "Księga Powtórzonego Prawa"),
    ("Joz", "Księga Jozuego"),
    ("Sdz", "Księga Sędziów"),
    ("Rt", "Księga Rut"),
    ("1 Sm", "Pierwsza Księga Samuela"),
    ("2 Sm", "Druga Księga Samuela"),
    ("1 Krl", "Pierwsza Księga Królewska"),
    ("2 Krl", "Druga Księga Królewska"),
    ("1 Krn", "Pierwsza Księga Kronik"),
    ("2 Krn", "Druga Księga Kronik"),
    ("Ezd", "Księga Ezdrasza"),
    ("Ne", "Księga Nehemiasza"),
    ("Tb", "Księga Tobiasza"),
    ("Jdt", "Księga Judyty"),
    ("Est", "Księga Estery"),
    ("1 Mch", "Pierwsza Księga Machabejska"),
    ("2 Mch", "Druga Księga Machabejska"),
    ("Hi", "Księga Hioba"),
    ("Ps", "Księga Psalmów"),
    ("Prz", "Księga Przysłów"),
    ("Koh", "Księga Koheleta"),
    ("Pnp", "Pieśń nad Pieśniami"),
    ("Mdr", "Księga Mądrości"),
    ("Syr", "Mądrość Syracha"),
    ("Iz", "Księga Izajasza"),
    ("Jr", "Księga Jeremiasza"),
    ("Lm", "Lamentacje"),
    ("Ba", "Księga Barucha"),
    ("Ez", "Księga Ezechiela"),
    ("Dn", "Księga Daniela"),
    ("Oz", "Księga Ozeasza"),
    ("Jl", "Księga Joela"),
    ("Am", "Księga Amosa"),
    ("Ab", "Księga Abdiasza"),
    ("Jon", "Księga Jonasza"),
    ("Mi", "Księga Micheasza"),
    ("Na", "Księga Nahuma"),
    ("Ha", "Księga Habakuka"),
    ("So", "Księga Sofoniasza"),
    ("Ag", "Księga Aggeusza"),
    ("Za", "Księga Zachariasza"),
    ("Ml", "Księga Malachiasza"),
    ("Mt", "Ewangelia według św. Mateusza"),
    ("Mk", "Ewangelia według św. Marka"),
    ("Łk", "Ewangelia według św. Łukasza"),
    ("J", "Ewangelia według św. Jana"),
    ("Dz", "Dzieje Apostolskie"),
    ("Rz", "List do Rzymian"),
    ("1 Kor", "Pierwszy List do Koryntian"),
    ("2 Kor", "Drugi List do Koryntian"),
    ("Ga", "List do Galatów"),
    ("Ef", "List do Efezjan"),
    ("Flp", "List do Filipian"),
    ("Kol", "List do Kolosan"),
    ("1 Tes", "Pierwszy List do Tesaloniczan"),
    ("2 Tes", "Drugi List do Tesaloniczan"),
    ("1 Tm", "Pierwszy List do Tymoteusza"),
    ("2 Tm", "Drugi List do Tymoteusza"),
    ("Tt", "List do Tytusa"),
    ("Flm", "List do Filemona"),
    ("Hbr", "List do Hebrajczyków"),
    ("Jk", "List św. Jakuba Apostoła"),
    ("1 P", "Pierwszy List św. Piotra Apostoła"),
    ("2 P", "Drugi List św. Piotra Apostoła"),
    ("1 J", "Pierwszy List św. Jana Apostoła"),
    ("2 J", "Drugi List św. Jana Apostoła"),
    ("3 J", "Trzeci List św. Jana Apostoła"),
    ("Jud", "List św. Judy Apostoła"),
    ("Ap", "Apokalipsa św. Jana"),
]

ABBR_TO_NAME = dict(BOOK_ORDER)
VALID_ABBRS = set(ABBR_TO_NAME.keys())
